version: 2
updates:
- package-ecosystem: maven
  directory: "/flatpak-dev-shim/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
